channels:
  - conda-forge
  - conda
dependencies:
  - cffi=1.11.5=py37h74b6da3_1
  - ipython=6.5.0=py37_0
  - ipywidgets=7.4.1=py37_0
  - numpy=1.15.1=py37ha559c80_0
  - pillow=5.2.0=py37h08bbbbd_0
  - scipy=1.1.0=py37h4f6bf74_1